version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: 'LIB'
      POSTGRES_USER: 'USER'
      POSTGRES_PASSWORD : 'PASSWORD'
    ports:
      - "5434:5432"
  flask_web:
    build: .
    command: python run.py
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
